<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1d0xtwR\installerPimcore_Bundle_InstallBundle_InstallerKernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1d0xtwR/installerPimcore_Bundle_InstallBundle_InstallerKernelProdDebugContainer.php') {
    touch(__DIR__.'/Container1d0xtwR.legacy');

    return;
}

if (!\class_exists(installerPimcore_Bundle_InstallBundle_InstallerKernelProdDebugContainer::class, false)) {
    \class_alias(\Container1d0xtwR\installerPimcore_Bundle_InstallBundle_InstallerKernelProdDebugContainer::class, installerPimcore_Bundle_InstallBundle_InstallerKernelProdDebugContainer::class, false);
}

return new \Container1d0xtwR\installerPimcore_Bundle_InstallBundle_InstallerKernelProdDebugContainer([
    'container.build_hash' => '1d0xtwR',
    'container.build_id' => '56605a64',
    'container.build_time' => 1622184232,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1d0xtwR');
